### ISSUE TITLE
GestureDetector in Marker not works

### ISSUE THREAD

**Issue by wenerme** [apptreesoftware/flutter_map#101]
How can I get an event of marker tap or long press ?

**Comment by johnpryan** [comment]
When you build a Marker, you use any widget:

```
      return new Marker(
        width: 80.0,
        height: 80.0,
        point: latlng,
        builder: (ctx) => new Container(
          child: new FlutterLogo(),
        ),
      );
```

So instead of `FlutterLogo` you could use `InkWell` or some other widget with an `onTap` method. Detecting long presses might require you to use your own GestureRecognizer.

Moving this to https://github.com/apptreesoftware/flutter_map/issues/102

**Comment by wenerme** [comment]
The top level widget is GestureDetector, all action is not triggered, but the on tap of map is triggered.

**Comment by johnpryan** [comment]
You should be seeing a tap event on the "innermost" widget (your marker) if it's handling the tap event:

> The pointer down event (and subsequent events for that pointer) are then dispatched to the innermost widget found by the hit test.

https://flutter.io/gestures/

**Comment by wenerme** [comment]
@johnpryan 

![image](https://user-images.githubusercontent.com/1777211/45965324-bfaa5180-c05a-11e8-8b21-9f316f61c05d.png)

![image](https://user-images.githubusercontent.com/1777211/45965375-de104d00-c05a-11e8-9dfa-06822671eb99.png)

![image](https://user-images.githubusercontent.com/1777211/45965394-ef595980-c05a-11e8-82f2-68be68007c3e.png)


Both tap will not trigger. Only the onTap of MapOptions was triggered.

**Comment by johnpryan** [comment]
I can't see why this isn't working for you - can you verify that the example is working with your setup? https://github.com/apptreesoftware/flutter_map/pull/103

**Comment by wenerme** [comment]
I remove the `interactive: false` then works, I thought disable interactive is disable the map's interactive not marker's.
