### ISSUE TITLE
Bug: You can't put a row in a MapPlugin

### ISSUE THREAD

**Issue by lsaudon** [apptreesoftware/flutter_map#108]
I'm trying to have a row that contains a textfield and a iconButton like the one below.
```dart
body: Column(
        children: <Widget>[
          Flexible(
            child: new FlutterMap(
              mapController: mapController,
              options: new MapOptions(
                center: new LatLng(47.10347, 5.48075),
                zoom: 5.0,
                plugins: [
                  new SearchBarPlugin(),
                ],
              ),
              layers: [
                new TileLayerOptions(
                  urlTemplate:
                      "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                  subdomains: ['a', 'b', 'c'],
                ),
                new SearchBarPluginOptions(
                    TextField(
                      decoration: InputDecoration(
                        border: InputBorder.none,
                        hintText: 'Saisissez votre recherche',
                      ),
                    ),
                    IconButton(
                      icon: Icon(
                        Icons.my_location,
                        color: Color.fromRGBO(0, 178, 169, 1.0),
                      ),
                      onPressed: () {},
                    )),
              ],
            ),
          ),
        ],
      ),
```

```dart
class SearchBarPluginOptions extends LayerOptions {
  final TextField textField;
  final IconButton iconButton;

  SearchBarPluginOptions(this.textField, this.iconButton);
}

class SearchBarPlugin implements MapPlugin {
  @override
  Widget createLayer(LayerOptions options, MapState mapState) {
    if (options is SearchBarPluginOptions) {
      return Row(
        children: <Widget>[
          Container(
            decoration: BoxDecoration(
              color: Color.fromRGBO(255, 255, 255, 0.9),
              borderRadius: BorderRadius.circular(25.0),
            ),
            margin: EdgeInsets.all(15.0),
            padding: EdgeInsets.symmetric(horizontal: 20.0),
            child: options.textField,
          ),
          Container(
            decoration: BoxDecoration(
              color: Color.fromRGBO(255, 255, 255, 0.9),
              borderRadius: BorderRadius.circular(25.0),
            ),
            margin: EdgeInsets.all(15.0),
            child: options.iconButton,
          ),
        ],
      );
    }
    throw ("Unknown options type for MyCustom plugin: $options");
  }

  @override
  bool supportsLayer(LayerOptions options) {
    return options is SearchBarPluginOptions;
  }
}
```
I have the following errors.

flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: BoxConstraints forces an infinite width.
flutter: These invalid constraints were provided to RenderAnimatedOpacity's layout() function by the
flutter: following function, which probably computed the invalid constraints in question:
flutter:   _RenderDecoration._layout.layoutLineBox (package:flutter/src/material/input_decorator.dart:808:11)
flutter: The offending constraints were:
flutter:   BoxConstraints(w=Infinity, 0.0<=h<=605.0)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:514:9)
flutter: #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:555:21)
flutter: #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:561:6)
flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1478:24)
flutter: #4      _RenderDecoration._layout.layoutLineBox (package:flutter/src/material/input_decorator.dart:808:11)
flutter: #5      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:839:18)
flutter: #6      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:969:44)
flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #14     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #18     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #20     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #22     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #28     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:13)
flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #30     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #32     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
flutter: #33     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
flutter: #34     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
flutter: #35     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
flutter: #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #40     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #48     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #61     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2884:13)
flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #63     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #65     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
flutter: #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #75     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
flutter: #76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
flutter: #77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
flutter: #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
flutter: #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
flutter: #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #85     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #86     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #87     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   _RenderDecoration#91b5e relayoutBoundary=up13 NEEDS-LAYOUT NEEDS-PAINT
flutter:   creator: _Decorator ← InputDecorator ← AnimatedBuilder ← Listener ← RawGestureDetector ←
flutter:   GestureDetector ← IgnorePointer ← Semantics ← TextField ← Padding ← DecoratedBox ← Padding ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=605.0)
flutter:   size: MISSING
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:   RenderRepaintBoundary#4fdd6 NEEDS-LAYOUT NEEDS-PAINT
flutter:     RenderPointerListener#81b5e NEEDS-LAYOUT NEEDS-PAINT
flutter:       RenderSemanticsAnnotations#00183 NEEDS-LAYOUT NEEDS-PAINT
flutter:         RenderIgnorePointer#4b69d NEEDS-LAYOUT NEEDS-PAINT
flutter:           RenderLeaderLayer#1d7e1 NEEDS-LAYOUT NEEDS-PAINT
flutter:   RenderAnimatedOpacity#ef84e NEEDS-LAYOUT NEEDS-PAINT
flutter:     RenderParagraph#10c26 NEEDS-LAYOUT NEEDS-PAINT
flutter:   RenderConstrainedBox#7366f NEEDS-LAYOUT NEEDS-PAINT
flutter:   RenderCustomPaint#9dd7a NEEDS-LAYOUT NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: _RenderDecoration#91b5e relayoutBoundary=up13 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#471f9 relayoutBoundary=up12 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#bc8aa relayoutBoundary=up11 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#9d0a0 relayoutBoundary=up10 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPadding#04c22 relayoutBoundary=up9 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#a0a76 relayoutBoundary=up8 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPadding#3e408 relayoutBoundary=up7 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#3d752 relayoutBoundary=up6 NEEDS-PAINT
flutter: Another exception was thrown: BoxConstraints forces an infinite width.
flutter: Another exception was thrown: RenderBox was not laid out: _RenderDecoration#80b79 relayoutBoundary=up13 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#b973b relayoutBoundary=up12 NEEDS-PAINT
Reloaded 0 of 474 libraries in 433ms.
flutter: Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#21012 relayoutBoundary=up11 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#2a1a9 relayoutBoundary=up10 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPadding#b47b9 relayoutBoundary=up9 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#092af relayoutBoundary=up8 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPadding#571d9 relayoutBoundary=up7 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#fb39d relayoutBoundary=up6 NEEDS-PAINT
flutter: Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The method '>' was called on null.

I don't know if it's a bug or a parameter that's missing on my side.

**Comment by lsaudon** [comment]
Solution: I wrap a container in Flexible Widget
```dart
return Row(
        children: <Widget>[
          Flexible(
            child: Container(
              decoration: BoxDecoration(
                color: Color.fromRGBO(255, 255, 255, 0.9),
                borderRadius: BorderRadius.circular(25.0),
              ),
              margin: EdgeInsets.all(15.0),
              padding: EdgeInsets.symmetric(horizontal: 20.0),
              child: options.textField,
            ),
          ),
          Container(
            decoration: BoxDecoration(
              color: Color.fromRGBO(255, 255, 255, 0.9),
              borderRadius: BorderRadius.circular(25.0),
            ),
            margin: EdgeInsets.all(15.0),
            child: options.iconButton,
          ),
        ],
      );
```

**Comment by alfanhui** [comment]
Can OP edit his original post to remove the links, it is linking all the github issues into this one.
