### ISSUE TITLE
Marker's anchor field can be public

### ISSUE THREAD

**Issue by tomwyr** [apptreesoftware/flutter_map#123]
Marker is basically data holder class and all the other fields are public already. It would be nice to have access to all its fields after creation.

**Comment by csjames** [comment]
+1

**Comment by tomwyr** [comment]
I've added [a commit](https://github.com/tomwyr/flutter_map/commit/8eab0f4674a1f490f77c1296ae049643c26d470a) that fixes this and changes the way `Anchor` is created (right now it's possible to pass both *anchor* and *anchorOverride* to the `Marker`'s constructor at the same time ). Please take a look and decide if it's worth PRing it.

**Comment by vinicentus** [comment]
+1

**Comment by johnpryan** [comment]
Can you make a PR for that? I am currently very busy this month but I can try to make time to release some of the outstanding PRs we have and would like to include this.
