### ISSUE TITLE
Can't get events on markers working...

### ISSUE THREAD

**Issue by ibrierley** [apptreesoftware/flutter_map#135]
I am including some Markers in a new FlutterMap as follows (which display fine)...both with a GestureDirector, as well as an IconButton, but nothing seems to cause any event to fire. Have also tried an Inkwell.

If I include an IconButton for example outside of the FlutterMap it all works fine. So it feels like somehow the map is intercepting the presses (as I can move about the map fine), and not acting on the one below. 
Is there something I'm doing wrong there ?

```
new MarkerLayerOptions(
          markers: [
            new Marker(
              width: 20.0,
              height: 20.0,
              point: centerLatLng,
              builder: (ctx) =>
              new Container(
                child: new GestureDetector(
                  child: new Transform(
                    transform: new Matrix4.rotationZ(0.1),
                    child: new IconButton(
                      icon: Icon(Icons.location_on),
                      color: Colors.deepPurple,
                      tooltip: 'This is you',
                      onPressed: () {
                        print("Pressed...");
                      },
                    ),
                  ),
                  onTap: () { print("tapped");},
                ),
              ),
            )
          ],
        ),
```

**Comment by RaimundWege** [comment]
Does it work when you swap the GestureDetector with the Container widget?

**Comment by ibrierley** [comment]
Hi, it's still the same, however, I think I'm getting to the problem now...

Devil is always in the detail, especially stuff I've not included here as I thought irrelevant!

I also have a polyline on an upper layer (that's nowhere near the Icon)

So layer wise I did have 
[TileLayerOptions,
MarkerLayerOptions,
PolylineLayerOptions]

If I swap to 
[TileLayerOptions,
PolyLineLayerOptions,
MarkerLayerOptions]

Clicks come through. So even though the polyline is just a line, it was intercepting the events as it was at a higher layer ?

This obvious works as a workaround to the problem, but does anyone know why a polyline/layer would not allow events to come through (as there are no gestures configured for it). I had tried to kind of wrap it inside an IgnorePointer widget, but couldn't seem to get that to play with it.

**Comment by johnpryan** [comment]
All layers will block events if they are "above" other layers. Under the hood this is just using the native gesture detection system in Flutter using a Stack.

**Comment by geisterfurz007** [comment]
Would it be an option to pass a `clickThrough` option to all layers and if true, wrap the Stack with [IgnorePointer](https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html)? That would make for even more flexibility by being able to draw circles over markers for example while still maintaining clickability for lower marker layers.  
The current behaviour is a little unexpected and it took me some time to figure out that it was a small green dot I put somewhere for testing that was the cause for tap events on markers not being registered.

If the idea above would be acceptable, I would try to set some time aside to implement it this weekend.
