### ISSUE TITLE
Scale circle marker with zoom

### ISSUE THREAD

**Issue by Noller-BASCO** [apptreesoftware/flutter_map#146]
Thank you for adding the circle marker layer! The ability to have the circle radius chance with the zoom level would be very useful.

**Comment by johnpryan** [comment]
Cool - you can listen to the map controller for changes and update the circle layer however you wish! There's currently no example of this but it should be the same as any other update using setState()

**Comment by Noller-BASCO** [comment]
@johnpryan The behavior I was requesting looks to be implemented in leaflet as [circle](https://leafletjs.com/reference-1.3.4.html#circle) where you pass a radius in meters as opposed to pixels. 
Using the map controller I can receive a call backs for map position and zoom but could you point me in the right direction to convert this information into pixels per meter?

**Comment by christocracy** [comment]
I'm trying to draw circular geofences on the Map, where radius is in *meters*.

The `CircleMarker` `radius` should be measured in *meters* -- not *pixels*.  This is the case for *every* Map API (GoogleMaps, MapBox, Leaflet, etc).

**Comment by johnpryan** [comment]
sorry - i don't know much about this use-case

**Comment by christocracy** [comment]
The default use-case of rendering a `Circle` on a map is to measure that `Circle`'s radius in *meters*.

- When you zoom out, the circle gets *smaller*.
- When you zoom in, the circle gets *bigger*.

Like this [`google.maps.Circle` example](https://developers.google.com/maps/documentation/javascript/examples/circle-simple)

**Comment by christocracy** [comment]
- [Leaflet Circle Example](
https://www.wrld3d.com/wrld.js/latest/docs/examples/adding-a-leaflet-circle/)
- [Mapbox Circle Example](
https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/)

Everybody will expect a Circle radius to be measured in *meters* — not *pixels*.

**Comment by christocracy** [comment]
@artob Thanks for the heads up.
