### ISSUE TITLE
Is it possible to mark countries with colors?

### ISSUE THREAD

**Issue by HerrNiklasRaab** [apptreesoftware/flutter_map#158]
I plan to use this plugin with Mapbox, but is it possbile to mark for example a whole country green, a link or small example would be great, on how to achieve this.

**Comment by figux01** [comment]
we need help. For me , i try to load GeoJson file but don't know how to do it

**Comment by HerrNiklasRaab** [comment]
Ok, thanks for your response and your idea, I will investigate on this.

**Comment by HerrNiklasRaab** [comment]
@johnpryan Hi there, thanks again for the tip, just started to implement this feature. Found great provider for GeoJson: https://geojson-maps.ash.ms/. But i have no idea on how to combine this with flutter_map.

**Comment by HerrNiklasRaab** [comment]
Just read your last comment again, i have to parse the json and create a polyline layer. Sorry!

**Comment by ndarilek** [comment]
@HerrNiklasRaab, did you ever implement a GeoJSON layer? In a similar boat myself, and will probably get to it eventually, but if *you* did then it might make a great contribution if you're able. :)
