### ISSUE TITLE
update README urlTemplate

### ISSUE THREAD

**Issue by jpgilchrist** [apptreesoftware/flutter_map#16]
Was following the instructions, but 'https://api.tiles.mapbox/v4...' didn't work. I had to remove the 'tiles' portion... so it was: "https://api.mapbox.com/v4/{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}"

**Comment by johnpryan** [comment]
Weird! It doesn't seem to matter for me. I am using:

```
https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}
```

but the `.tiles` can be removed, and matches [the documentation](https://www.mapbox.com/api-documentation/#maps)

```
https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}
```

I also see `api.tiles` in [various places](https://www.mapbox.com/mapbox-gl-js/example/simple-map/) in their documentation so I'm not sure what the difference is to be honest.

**Comment by jpgilchrist** [comment]
Hm I just created the account and it kept giving me a 401 with the tiles included.

**Comment by johnpryan** [comment]
Ok, not sure what's going on with my setup, but I think 090d533 is the correct change. Thanks for filing an issue!
