### ISSUE TITLE
Include google maps api

### ISSUE THREAD

**Issue by GENL** [apptreesoftware/flutter_map#165]
Is there a way to use google maps with flutter_map ?
I realy want to use flutter_map librairy. But as i can see, it works with mapbox and others. It is possible to manipulate google maps with flutter_map package ?
Thanks!

**Comment by johnpryan** [comment]
no there's not. Google doesn't allow their tiles to be used as standalone tiles

**Comment by GENL** [comment]
Okay thanks. Let's go with mapbox.
I took a look at the mapbox doc, the map is pretty good with lots of places. Tell me is there some big differences in functionality between mapbox and google maps?

**Comment by johnpryan** [comment]
You'll have to be more specific... Google maps is actually a large API with places search, etc.  MapBox is mainly used for displaying map tiles but has other APIs as well. You'll have to look into the docs for your use-case to compare

**Comment by GENL** [comment]
Okay! Thanks a lot.
