### ISSUE TITLE
exception with Dart2.0

### ISSUE THREAD

**Issue by herry1234** [apptreesoftware/flutter_map#17]
hit exception when i am trying to run the example code with Dart2.0.

flutter --version
Flutter 0.1.8-pre.43 • channel master • https://github.com/flutter/flutter.git
Framework • revision fe334e1652 (2 weeks ago) • 2018-03-02 17:54:51 -0800
Engine • revision 97b22348c8
Tools • Dart 2.0.0-dev.32.0.flutter-ee15c8eb68

I/flutter (12109): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12109): The following assertion was thrown building Container:
I/flutter (12109): type 'Bounds<num>' is not a subtype of type 'Bounds<double>' where
I/flutter (12109):   Bounds is from package:flutter_map/src/core/bounds.dart
I/flutter (12109):   num is from dart:core
I/flutter (12109):   Bounds is from package:flutter_map/src/core/bounds.dart
I/flutter (12109):   double is from dart:core
I/flutter (12109): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12109): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12109): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12109):   https://github.com/flutter/flutter/issues/new
I/flutter (12109): When the exception was thrown, this was the stack:
I/flutter (12109): #0      new Bounds (package:flutter_map/src/core/bounds.dart:11:20)
I/flutter (12109): #1      SphericalMercator._bounds (package:flutter_map/src/geo/crs/crs.dart:86:39)
I/flutter (12109): #2      SphericalMercator._bounds (package:flutter_map/src/geo/crs/crs.dart:86:25)
I/flutter (12109): #3      SphericalMercator.bounds (package:flutter_map/src/geo/crs/crs.dart:93:32)
I/flutter (12109): #4      Crs.getProjectedBounds (package:flutter_map/src/geo/crs/crs.dart:43:24)
I/flutter (12109): #5      MapState.getPixelWorldBounds (package:flutter_map/src/map/map.dart:116:24)
I/flutter (12109): #6      _TileLayerState._resetGrid (package:flutter_map/src/layer/tile_layer.dart:173:22)
I/flutter (12109): #7      _TileLayerState._setView (package:flutter_map/src/layer/tile_layer.dart:85:7)
I/flutter (12109): #8      _TileLayerState._resetView (package:flutter_map/src/layer/tile_layer.dart:77:10)
I/flutter (12109): #9      _TileLayerState.initState (package:flutter_map/src/layer/tile_layer.dart:62:5)
I/flutter (12109): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:14)
I/flutter (12109): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (12109): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (12109): #13     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4716:32)
I/flutter (12109): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (12109): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (12109): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (12109): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (12109): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (12109): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (12109): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (12109): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (12109): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
I/flutter (12109): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (12109): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (12109): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
I/flutter (12109): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (12109): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (12109): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (12109): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (12109): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (12109): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
I/flutter (12109): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (12109): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (12109): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (12109): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (12109): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (12109): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (12109): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (12109): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (12109): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (12109): #41     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
I/flutter (12109): #42     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
I/flutter (12109): #43     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
I/flutter (12109): #44     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter (12109): #45     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
I/flutter (12109): #46     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter (12109): #47     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
I/flutter (12109): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #49     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
I/flutter (12109): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #51     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12109): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #53     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
I/flutter (12109): #54     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:256:7)
I/flutter (12109): #55     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter (12109): #56     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter (12109): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #58     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #60     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #61     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141:11)
I/flutter (12109): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #63     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #65     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #67     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #69     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #71     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #72     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2713:13)
I/flutter (12109): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #74     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #76     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:509:15)
I/flutter (12109): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #78     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #80     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #82     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #84     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #86     __RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin^^#U0^#U0.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12109): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12109): #88     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter (12109): #89     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (12109): #90     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (12109): #91     _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (12109): #92     ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622:13)
I/flutter (12109): #93     _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (12109): #94     ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (12109): #95     ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (12109): #96     ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (12109): #98     _Timer._runTimers (dart:isolate/timer_impl.dart:382:19)
I/flutter (12109): #99     _Timer._handleMessage (dart:isolate/timer_impl.dart:416:5)
I/flutter (12109): #100    _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
I/flutter (12109): (elided one frame from package dart:async)
I/flutter (12109):

**Comment by EasonPai** [comment]
I have the same issue.

flutter --version

```
Flutter 0.2.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision b397406561 (29 hours ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357
```

**Comment by bramvbilsen** [comment]
I'm experiencing similar issues.

**Comment by mauroeme** [comment]
same for me. good job either way.

**Comment by yathit** [comment]
Same problem.

**Comment by jpagex** [comment]
I experienced it too.

**Comment by nitneuq33** [comment]
same...   hope this issue will be correct quickly

**Comment by johnpryan** [comment]
Hey all - until we find some time to fix this (very soon) you can run the app using the `--no-preview-dart-2` flag:

```
flutter run --no-preview-dart-2
```

**Comment by johnpryan** [comment]
This should be fixed.
