### ISSUE TITLE
Preload tiles from an array of latlngs ?

### ISSUE THREAD

**Issue by ibrierley** [apptreesoftware/flutter_map#170]
I can see in the code there is a call to load an image/url depending on a point in the tilemap layer.

One thing I was wondering about, was the ability to preload a set of images, based on an array of latlongs, or an area (eg topleft, bottomright).

Reasoning is, I'm developing an app where offline is needed, and currently before I go ofline, I drag around a certain area to load the images into cache. Then the map works offline.

I'm unsure if this should be part of the core flutter_map though, as it feels like it could easily be abused (downloading too many tiles). Maybe there could be a delay added to be kind to the tileservers and a max tiles restriction ? I looked a the plugin lib, but didn't see how I could manage via that to access the tilelayer code.

Completely understand if it's not desirable.

**Comment by johnpryan** [comment]
Have you checked out the offline tile example? I suspect that will work for your use-case.

**Comment by gimox** [comment]
I think that a sortvof preliading and casching is a good think. So offline map are good molto for limited zone where tiles are very light under 100mb. So i m thinking somethink like:
- caching leader tiles
- preloading other tiles near visibile area for a smonth gestures

What about stsrt using cachednetwork plugin?

**Comment by ibrierley** [comment]
Am going to close this, although I still think it would be useful, especially using flutter_cache_manager, but it became too fiddly for me.

Just for info, I've gone with my own solution which lets me select an area via latlngs, download the tiles in advance (after deleting old set from a custom directory) using http.get & Io.File..writeAsBytesSync, and then if the app detects no data available, it changes fluttermap offline mode and uses a local urlTemplate, if there is data it uses a remote urlTemplate.
