### ISSUE TITLE
Improve Pinch to zoom

### ISSUE THREAD

**Issue by johnpryan** [apptreesoftware/flutter_map#171]
The map should zoom directly to the point where the user is pinching.

**Comment by johnpryan** [comment]
Marking this as "help wanted" for any Leaflet / Map / Gesture experts.

**Comment by tomwyr** [comment]
It's been implemented in #121. PR awaits merge/close for some time.

**Comment by ibrierley** [comment]
Tried this one out yesterday, very nice to use.

Ian
