### ISSUE TITLE
Flutter: Location package Not working on First Time App Install

### ISSUE THREAD

**Issue by zhen1991** [apptreesoftware/flutter_map#175]
My current app uses the Location package to obtain the user's current latitude and longitude to be used to find nearby facilities.

This is the code I am using (similar to the example in the documentation)

 Map<String, double> _currentLocation;
  Map<String, double> _startLocation;

  StreamSubscription<Map<String, double>> _locationSubscription;
  String error;
  bool _permission = false;

  Location _location = new Location();

  // Platform messages are asynchronous, so we initialize in an async method.
  initPlatformState() async {
    Map<String, double> location;

    try {
      _permission = await _location.hasPermission();
      location = await _location.getLocation();

      error = null;
    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_DENIED') {
        error = 'Permission denied';
      } else if (e.code == 'PERMISSION_DENIED_NEVER_ASK') {
        error = 'Permission denied - please ask the user to enable it from the app settings';
      }

      location = null;
    }

    setState(() {
      _startLocation = location;
      print("Starting coordinates: ${_startLocation["latitude"]}, ${_startLocation["longitude"]}");
    });
  }

@override
  void initState() {
    super.initState();

      initPlatformState();

      _locationSubscription =
          _location.onLocationChanged().listen((Map<String,double> result) {
            setState(() {
              _currentLocation = result;
              print("Current coordinates: ${_currentLocation["latitude"]}, ${_currentLocation["longitude"]}");
            });
          });
  }

The only problem I am facing is that whenever there is a fresh install of a new apk of the app, the app does not find the location after location permission has been granted.

After location has been granted I have set up a print statement to print out the user's location but for some reason it is not printing anything the first time only. After I restart the app then it prints out the location just fine.

**Comment by johnpryan** [comment]
This sounds like an issue with the location package - Did you file an issue there?

**Comment by zhen1991** [comment]
Yes i used lication package !!
Any solution to this ?? 
Is there a way to solve this ??
Thnx :)

**Comment by johnpryan** [comment]
Please file an issue here: https://github.com/Lyokone/flutterlocation
