### ISSUE TITLE
Map view removes tiles when zooming to new zoom levels

### ISSUE THREAD

**Issue by chances** [apptreesoftware/flutter_map#2]
Steps to reproduce:

1. Run example
2. Let default map view tiles load
3. Pinch to zoom into the map at a new zoom level
4. Observe the previously loaded tiles disappear
5. Wait for new tiles to load
6. Observe new tiles fade in

This experience is jarring and can prevent me from seeing what I'm zooming into.

This issue can also be reproduced by zooming out from the initial map location to other zoom levels.

Instead the tiles should render as they do in Mapbox's [Raster tile source example](https://www.mapbox.com/mapbox-gl-js/example/map-tiles/). The old tiles remain rendered and are scaled to the current zoom level. New tiles at different zoom levels then fade in on top of the old tiles.

**Comment by johnpryan** [comment]
_TileLayerState doesn't support multiple "levels" properly yet.  Leaflet will render more then one "level" 

Currently, _TileLayerState calls `_setView` every time `build()` is called (https://github.com/apptreesoftware/flutter_map/blob/master/flutter_map/lib/src/layer/tile_layer.dart#L256) which causes the rest of the build method to only render the tiles that are at the current `_tileZoom`.

Leaflet uses a cache of each HTML elements to store tiles, which in Flutter, is just a cache of `Tile` objects, but I haven't quite figured out how Leaflet cleans up old tiles (not at the current z-index. So the solution here could be to always render all tiles in the cache, regardless of z-index, and set a timer to remove them from the cache when the z-index changes.

**Comment by johnpryan** [comment]
this is resolved by https://github.com/apptreesoftware/flutter_map/pull/5 - Like leaflet, we clear the tiles if the zoom level differs by more than a certain amount, but in general the image widgets should remain on the screen when the zoom level changes.
