### ISSUE TITLE
Callback for when a user pans the map

### ISSUE THREAD

**Issue by luccascorrea** [apptreesoftware/flutter_map#34]
Hi,

Is there a way to know when a user panned the map? My goal is to update the markers shown in the map if the user pans it. A callback that is called with the new coordinates of the center of the maps would be great. Is it possible?

Thanks!

**Comment by johnpryan** [comment]
Good idea! This isn't supported yet, but I don't think would be too difficult to implement.

**Comment by luccascorrea** [comment]
Thanks for the response! 
Could you give me some rough directions as to how this could be implemented? I took a look at the code and it seems to me that changing the GestureDetector returned in the FlutterMapState class so that the parameter onPanEnd is passed, which will then invoke the callback, might be a solution. Does that make sense to you? I just want to have a rough idea before I dive deeper into this.

Thanks!

**Comment by johnpryan** [comment]
I think there might be a simpler approach; MapState has an `onMoved` stream (currently only used internally) but this could be exposed by the MapController interface since it has access to MapState:

```
class MapControllerImpl implements MapController {
  MapState state;

  void move(LatLng center, double zoom) {
    state.move(center, zoom);
  }
}
```

would change to something like

```
class MapControllerImpl implements MapController {
  MapState state;

  void move(LatLng center, double zoom) {
    state.move(center, zoom);
  }
  Stream<LatLng> get onMoved => state.onMoved;
}
```

the MapState.onMoved stream is a Stream<Null> so that will need to change to Stream<LatLng> as well.

**Comment by johnpryan** [comment]
MapOptions now has `onPositionChanged` which exposes a callback.  Once the callback is invoked, you can use a `MapController` to get the current center and zoom level of the map
