### ISSUE TITLE
change the type of map

### ISSUE THREAD

**Issue by nitneuq33000** [apptreesoftware/flutter_map#41]
How to add a hybrid map ?

**Comment by avioli** [comment]
Please, be more specific. Could you define what a "hybrid map" is meant to be?

**Comment by nitneuq33000** [comment]
It's a map with 2 layers : sattelite view + data ( roads, city name etc )

Le lun. 28 mai 2018 à 01:29, Evo Stamatov <notifications@github.com> a
écrit :

**Comment by johnpryan** [comment]
Does that work?

**Comment by nitneuq33000** [comment]
For this, I used map_view package but the map only work in full screen and
it's not customisable in a widget.

**Comment by johnpryan** [comment]
This should be possible with flutter_map by just adding two LayerOptions objects to your layers property in the FlutterMap constructor

**Comment by johnpryan** [comment]
Moving this to https://github.com/apptreesoftware/flutter_map/issues/44 to provide an example of this with flutter_map
