### ISSUE TITLE
min/max Zoom constraints

### ISSUE THREAD

**Issue by alfanhui** [apptreesoftware/flutter_map#42]
Hello, 

Thanks for your work on this plugin. 

Maybe I'm missing something, but I cant seem to stop pinch-zoom when setting min/max constraints. The only thing that appears to abide is the default zoom variable. 

```
          FlutterMap(
                options: new MapOptions(
                  center: new LatLng(51.457282, -2.586597),
                  maxZoom: 15.0, 
                  minZoom: 15.0,
                  zoom: 15.0,
                ),
                layers: [
                  new TileLayerOptions(
                    maxZoom: 15.0,
                      urlTemplate:
                      "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                      subdomains: ['a'])
                ]
          )
```

I'll see about digging around in the code for a fix, but I am new to contributing to any open-source project.

**Comment by johnpryan** [comment]
Good catch - this is something we intend to fix :)
