### ISSUE TITLE
Moving markers without redrawing whole map

### ISSUE THREAD

**Issue by maral** [apptreesoftware/flutter_map#55]
Is there a way to change marker position? We would like to show user's current position and update it regularly. I noticed current location is on the roadmap, I just wonder if there is some workaround. My another idea was to make the location dot a separate widget on top of the map and update its location with MapController. Any ideas?

**Comment by maral** [comment]
Also, marker grouping would be nice, and I think more control over the markers would solve this too.

**Comment by johnpryan** [comment]
You can do this just by changing the marker locations passed to the widget in a setState().  No need to use the controller for this, since the MarkerLayer widget is stateless.

**Comment by johnpryan** [comment]
@maral Did that work for you?

**Comment by johnpryan** [comment]
awesome 😎
