### ISSUE TITLE
How to Draw circle on the map

### ISSUE THREAD

**Issue by qingxo** [apptreesoftware/flutter_map#72]
There is the PolylineLayerOptions to draw the many line on the map,
but how to draw a circle on the map?

**Comment by johnpryan** [comment]
Check out the plugin API https://github.com/apptreesoftware/flutter_map/blob/master/lib/src/plugins/plugin.dart to access the MapState object similar to the polyline layer. The polyline layer just draws lines using Flutter's CustomPainter class.
