### ISSUE TITLE
Add double-tap to zoom

### ISSUE THREAD

**Issue by vinicentus** [apptreesoftware/flutter_map#73]
It would be nice to be able to double-tap on the map to zoom in on that spot. How hard would this be to implement? Maybe add it as a default feature?

**Comment by johnpryan** [comment]
Good idea!  Yes this is possible.  The GestureDetector widget we use could have a `onDoubleTap` handler that zooms the map by some amount

**Comment by vinicentus** [comment]
Wrote some code, but not completely sure I did the calculations for zooming right (zooming the right amount). It seems fine though.
