### ISSUE TITLE
Moving markers

### ISSUE THREAD

**Issue by vinicentus** [apptreesoftware/flutter_map#74]
What would be a good way to add moving markers? I'd like to update them based on an mqtt stream...

**Comment by johnpryan** [comment]
Moving markers can be implemented by simply calling setState() and updating their position on the map.

**Comment by vinicentus** [comment]
Yep, already tried that earlier.
I have really many markers on the map and one problem I currently have is that I have to identify every marker (to move the right marker on a specific event). Currently this is done by mapping the index of a marker in a list to an id, which definitely isn't the best way of doing it.

**Comment by agnoam** [comment]
> Yep, already tried that earlier.
> I have really many markers on the map and one problem I currently have is that I have to identify every marker (to move the right marker on a specific event). Currently this is done by mapping the index of a marker in a list to an id, which definitely isn't the best way of doing it.
> 
> EDIT: I have to remove the marker and insert a new one every time I want tom "move" it.
> EDIT 2: Maybe I could add an id variable to the markers?
> EDIT 3: Or I could change the list of markers to a map of markers and ids (strings).

I think that the best option is the EDIT 2. Is there any way to perform that ?
