### ISSUE TITLE
Add onTap InfoWIndow

### ISSUE THREAD

**Issue by rupert2133** [apptreesoftware/flutter_map#75]
Is there an option to show the InfoWindow when you tap on the map like in Google Maps?

**Comment by johnpryan** [comment]
No, but you can implement your own widget as a Marker that expands when you tap on it

**Comment by mehrdad1990** [comment]
> No, but you can implement your own widget as a Marker that expands when you tap on it

can you help implementing this info window that snaps to the marker and moves with the marker when you drag the map around. this info window should stay the same while zooming in and out. exactly like google map.
