### ISSUE TITLE
Add Polygons drawing

### ISSUE THREAD

**Issue by yostrokon** [apptreesoftware/flutter_map#77]
Is it possible to implement polygons drawing feature?

**Comment by yostrokon** [comment]
Actually, have an idea how to do this

Path path = new Path();
path.addPolygon(offsets, true);

final paint = Paint()
..style = PaintingStyle.fill;
canvas.drawPath(path, paint);

**Comment by johnpryan** [comment]
Yes, we have a polyline layer already that can be used as a reference

**Comment by yostrokon** [comment]
Sure. Just to find the time and selfeducate about git things )
Also have an idea to extend polyline to geodesic arcs based on same name plugin from leaflet.

**Comment by johnpryan** [comment]
Cool - you can use the [plugin API](https://github.com/apptreesoftware/flutter_map/blob/master/lib/src/plugins/plugin.dart) so that your layer can access the MapState similar to the polyline layer

**Comment by DanialV** [comment]
any improvements on this is there any way to draw a polygon on a map?

**Comment by ibrierley** [comment]
What can't you do with a polyline out of interest ? Is it the filling of it ?

**Comment by johnpryan** [comment]
@DanialV There's a polygon layer now https://github.com/johnpryan/flutter_map/blob/master/lib/src/layer/polygon_layer.dart

**Comment by billbull21** [comment]
> @DanialV There's a polygon layer now https://github.com/johnpryan/flutter_map/blob/master/lib/src/layer/polygon_layer.dart

how can i use it ? and how it work ? please guide me.
