### ISSUE TITLE
math.PI referenced on latlong version 0.4.x is not more supported on the latest version of flutter

### ISSUE THREAD

**Issue by AlexandreRoba** [apptreesoftware/flutter_map#82]
Hi,

Just upgraded to the latest version of flutter. math.PI has been removed and still referenced on older version of the latlong package. Apparently flutter_map reference version 0.4.0 and therefor I can't upgrade latlong as I will have a version conflict with the version used on flutter_map. Can we upgrade the flutter_map dependency?

thanks,

Alex.

**Comment by johnpryan** [comment]
fixed by https://github.com/apptreesoftware/flutter_map/pull/83 - thanks for the contribution!
