### ISSUE TITLE
Load only visible markers

### ISSUE THREAD

**Issue by vinicentus** [apptreesoftware/flutter_map#87]
How would one go about adding only the visible markers to the map. I basically want to have a list of markers, get the visible area of the map, and display only the markers that are within that box. I found that adding about 8300 markers was a bit too heavy...

**Comment by vinicentus** [comment]
How would I be able to get the corners of the visible portion of the map?

**Comment by johnpryan** [comment]
Interesting case. The map does filter out markers that aren't in view but we may need to add an API for getting the current bounding box from the controller to support this particular case so that you can filter the markers manually?

**Comment by yostrokon** [comment]
@johnpryan - just function to get the bounds. If there a way to get bounds of the map - these bounds can be send to the backend or whatever for the filrtering of the markers. (I have DB with the 25M markers and realtime connections and change)

**Comment by johnpryan** [comment]
sounds reasonable, we accept pull requests :)

**Comment by yostrokon** [comment]
@vinicentus check the clip things in the source - no computer till end of the week to do things. But clip should provide bounds

**Comment by vinicentus** [comment]
@yostrokon I probably won't have the time to look at this right now so maybe you could take a look?

**Comment by PiotrWpl** [comment]
Hi @yostrokon 
I couldn't find this clip things in the source? Could You help? thx!

**Comment by xqwzts** [comment]
I needed this tonight so put together quick PR: #99 

This exposes bounds both via the `MapController`: 
```
final LatLngBounds b = mapController.bounds;
```

and via the `onPositionChanged` callback:
```
new FlutterMap(
  mapController: mapController,
  options: new MapOptions(
    onPositionChanged: (mp) => print(mp.bounds),
  ),
);
```

**Comment by yostrokon** [comment]
@xqwzts 

if (options.onPositionChanged != null) {
      options.onPositionChanged(new MapPosition(center: center, zoom: zoom));
    }

what will happen when is a zoom only and position remains the same?

**Comment by xqwzts** [comment]
@yostrokon zooming triggers `MapState.move()` - which calls `onPositionChanged()`. So zooming and panning both trigger a position changed callback.

**Comment by vinicentus** [comment]
Thank you to everyone that contributed! Especially @xqwzts ;-)

**Comment by Huynh-Anh** [comment]
Hey @vinicentus is it possible to provide the solution you did to only make markers visible within the mapcontroller.bounds ?
Was it fast ? i believe youd have to setState at every position change to add or remove the markers that are visible ?

thanks
