### ISSUE TITLE
Markers position when zooming

### ISSUE THREAD

**Issue by marianoarga** [apptreesoftware/flutter_map#88]
Marker moves out when I zoom in or out, the position moves around, how can I keep it in the same coordinates? Is this spected? Tried OpenMaps and MapBox.
UPDATE:
This is only reproduce when using non "square" marker proportions...

```
new Marker(
  width: 180.0,
  height: 60.0,
...
```
Using square width and height seems to solve this issue.

![screenshot_1534384326](https://user-images.githubusercontent.com/1138627/44182616-16c51a00-a0de-11e8-99ad-656d1b214378.png)

![screenshot_1534384334](https://user-images.githubusercontent.com/1138627/44182602-06ad3a80-a0de-11e8-89f3-ccc6e13bd050.png)

**Comment by johnpryan** [comment]
This could be a math / rounding issue with coordinates. Can you make sure you are setting the pin position correctly and not to the center of the icon?

**Comment by marianoarga** [comment]
@johnpryan  I dont understand the question, the coordinates are ok, always comparing with a google maps pinned marker.
I have tried with widgets other than an Icon, Card for example, in order to be more descriptive about the marker inside the map, but got the same issue.
The marker itself seems to be pinned at the choosen widgets's center o bottom center, not sure, but in a squared size little Icon the bug isn't noticeable.

**Comment by johnpryan** [comment]
Sorry - I meant to say did you try setting the AnchorPos attribute of the marker? https://github.com/apptreesoftware/flutter_map/blob/master/lib/src/layer/marker_layer.dart#L70

**Comment by alfanhui** [comment]
I believe I have a fix for this, please bear with me a few days to prepare a PR.

**Comment by marianoarga** [comment]
@johnpryan AnchorPos solve this issue (Having non-square Marker), thank you.

**Comment by johnpryan** [comment]
cool, thanks for filing an issue!
