### ISSUE TITLE
Compatibility with windy.com

### ISSUE THREAD

**Issue by rafalbednarczuk** [apptreesoftware/flutter_map#92]
https://api4.windy.com/ uses leaflet, but they use some kind of authorization for their API. As far as I know there isn't template for tiles we can use without authorization. Is there a possibility to implement their tiles API in flutter_map plugin?

**Comment by johnpryan** [comment]
It doesn't look like Windy is more of a "plugin" for leaflet, rather than a standard map tile api (like Mapbox or OpenStreetMap)

**Comment by rafalbednarczuk** [comment]
Okay I see, as I need only wind data from this service I will try to implement to this plugin some kind of layer option for such a data. Thanks.

**Comment by AAverin** [comment]
@johnpryan what could be a viable option to run windy on flutter? Some kind of custom plugin on top of this map implementation?
As far as I understand, windy leaflet plugin can just put their weather visualisations on top of any leaflet map source, so this kind of speaks towards making a plugin. 

@rafalbednarczuk did you make any progress with this?

@mdorda did you guys already looked into flutter support?

**Comment by johnpryan** [comment]
I'm not sure how Windy works. Can you provide more information?

**Comment by AAverin** [comment]
@johnpryan https://github.com/windycom/API
from what I understood, it's just a library that built on top of Leaflet that also connects to their services for data and provides weather visualisations on top of the map
