### ISSUE TITLE
Not working on Dart SDK version 2.1.0-dev.3.0.flutter-760a9690c2

### ISSUE THREAD

**Issue by rupert2133** [apptreesoftware/flutter_map#97]
Version solving failed after adding `flutter_map ^0.0.1` dependencies

**Comment by RaimundWege** [comment]
Have you tried the newest version?

dependencies:
  flutter_map: ^0.1.1

**Comment by rupert2133** [comment]
Thanks! I haven't noticed the newest version, I tried the `0.1.1` version and there's no error now.. i hope they will change the installation guide in README from `0.0.1` to `0.1.1`
